import = [
  "./themes/themes/one_dark.toml"
]

[colors.primary]
background = "#17456e"
foreground = "#e6e6e6"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[shell]
args = []
program = "/bin/fish"

[window]
opacity = 0.8

[window.padding]
x = 8
y = 12
