import = [
  "./themes/themes/hypr.toml"
]

[colors.primary]
background = "#17456e"
foreground = "#e6e6e6"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
opacity = 0.7

[window.padding]
x = 8
y = 12
